version: 2
jobs:
  test: &default
    working_directory: ~/kuali-logger
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Configure private package registry
          command: |
            echo "//npm.kuali.co/:_authToken=\"$NPM_TOKEN\"" > .npmrc
            npm config set @kuali:registry='https://npm.kuali.co'
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test
  test-node6:
    <<: *default
    docker:
      - image: circleci/node:6
  test-node8:
    <<: *default
    docker:
      - image: circleci/node:8
  test-node10:
    <<: *default
    docker:
      - image: circleci/node:10
  test-node12:
    <<: *default
    docker:
      - image: circleci/node:12

  deploy:
    working_directory: ~/kuali-logger
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Configure public package registry
          command: |
            echo "//registry.npmjs.org/:_authToken=\"$PUBLIC_NPM_TOKEN\"" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

workflows:
  version: 2
  test_deploy:
    jobs:
      - test-node6
      - test-node8
      - test-node10
      - test-node12
      - deploy:
          requires:
            - test-node6
            - test-node8
            - test-node10
            - test-node12
          filters:
            branches:
              only: master
