version: 2
jobs:
  test:
    working_directory: ~/kuali-logger
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Configure private package registry
          command: |
            echo "//npm.kuali.co/:_authToken=\"$NPM_TOKEN\"" > .npmrc
            npm config set @kuali:registry='https://npm.kuali.co'
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Publish code coverage results
          command: yarn coverage:publish
      - store_artifacts:
          path: coverage
          destination: coverage
  deploy:
    working_directory: ~/kuali-logger
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: 'echo deploy'
workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master
