version: 2
jobs:
  test:
    working_directory: ~/kuali-logger
    docker:
      - image: circleci/node:4
    steps:
      - run:
          name: Environment
          command: |
            which node
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm --version
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Setup and initialize Code Climate test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Configure private package registry
          command: |
            echo "//npm.kuali.co/:_authToken=\"$NPM_TOKEN\"" > .npmrc
            npm config set @kuali:registry='https://npm.kuali.co'
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Publish code coverage results
          command: yarn coverage:publish
      - run:
          name: Report test results to Code Climate
          command: ./cc-test-reporter after-build -t lcov --exit-code $?
      - store_artifacts:
          path: coverage
          destination: coverage
  deploy:
    working_directory: ~/kuali-logger
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Configure public package registry
          command: |
            echo "//registry.npmjs.org/:_authToken=\"$PUBLIC_NPM_TOKEN\"" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish
workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
